language: csharp
solution: Calculator.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Calculator.sln
after_script:
  - xbuild Calculator.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe Calculator.Text/bin/Debug/Calculator.Text.dll
notifications:
  email:
    recipients:
      - Vincentwc_Huang@asus.com
    on_success: always
    on_failure: always
