language: csharp
solution: Calculator.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Calculator.sln
after_script:
  - xbuild Calculator.sln
  - nunit-console Calculator.Text/bin/Debug/Calculator.Text.dll
notifications:
  email:
    recipients:
      - ofnight0907@gmail.com
    on_success: always
    on_failure: always
